#!/usr/bin/env python
# -*- coding: utf-8 -*-

import signalfx
import json
from kubernetes import client, config
import math
import yaml
import os
import configparser
import sys


def load_yaml():
    with open("kfx.yaml", 'r') as file:
        command_tree = yaml.load(file)
        return command_tree


def parse_commands(command, commands):
   if commands and  commands.get("signalFlow"):
       return commands.get('signalFlow'), commands.get('metric')
   elif command == []:
       print "Kick Rocks!"
       exit()
   else:
       commands = commands.get(command[0])
       command = command[1:]
       return parse_commands(command, commands)


def all_clusters(token, sflow, metric_name):
    with signalfx.SignalFx().signalflow(token) as flow:
        computation = flow.execute(sflow)
        for msg in computation.stream():
            if isinstance(msg, signalfx.signalflow.messages.DataMessage):
                    os.system('clear')
                    print
                    print (" " * 40) + metric_name
                    print
                    clusters = {}
                    for tsid, value in msg.data.items():
                        metadata = computation.get_metadata(tsid)
                        used = int(value)
                        usedvisual = u"▇" * int(used)
                        node =  u'%-31s %s %s%%' % (metadata['host'], usedvisual, used)
                        if metadata['kubernetes_cluster'] in clusters:
                            clusters[metadata['kubernetes_cluster']].append(node)
                        else:
                            clusters[metadata['kubernetes_cluster']] = [node,]
                    for i in clusters:
                         print i
                         print "-----------------"
                         for x in clusters[i]:
                             print x
                         print


def main():

    try:
        command_tree = load_yaml()
        kfxconfig = configparser.ConfigParser()
        kfxconfig.read(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'kfx.config'))
        token  = kfxconfig['signalfx'].get('token')
        command = sys.argv[1:] 
        sflow, metric_name = parse_commands(command, command_tree)
        all_clusters(token, sflow, metric_name)
    except KeyboardInterrupt: # allows ctrl-c to exit gracefully without a stacktrace
        print
        exit(0)


if __name__ == "__main__":
    main() 
